use_frameworks!

target 'MJAiSearchSDK_Example' do
  pod 'MJAiSearchSDK', :path => '../'

  target 'MJAiSearchSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
